apiVersion: v1
kind: Service
metadata:
  name: cli250-web
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 3000
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    run: cli250-web
  type: NodePort
